### ISSUE TITLE
Absensi Siakad

### ISSUE THREAD

**Issue by sulthannaf** [Muammarzaki/siakad-presense-automation#1]
ada contact yang bisa dihubungi untuk mengolah absensi siakad kampus saya?

**Comment by Muammarzaki** [comment]
Maksud nya gimana nih bikin aplikasi absensi?

Pada tanggal Sab, 22 Apr 2023 02.28, Kocrek ***@***.***>
menulis:

**Comment by Muammarzaki** [comment]
coba hubungi aja No HP **08127724245** melalui wa
