### ISSUE TITLE
you are user of edge browser? so, you need the web driver? here it's

### ISSUE THREAD

**Issue by ariekany** [Muammarzaki/siakad-presense-automation#2]
link below is the documentation from microsoft
https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp

here is list of web driver, match the browser version and your edge before use it
https://msedgewebdriverstorage.z22.web.core.windows.net/

to use web driver, you are also need Selenium, here to download
https://www.selenium.dev/downloads

thanks

**Comment by Muammarzaki** [comment]
@arief-furqany give me a reason to use Microsoft edge , I think chrome is better at handling javascript

**Comment by ariekany** [comment]
Just make it, and that's better for public and society
